# Generated by Django 4.2.7 on 2023-12-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0003_compensation_firm_enroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='student',
        ),
    ]
